services:
  pldotnet-runtime:
    container_name: pldotnet-runtime
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        DOTNET_VERSION: ${DOTNET_VERSION}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
