x-interactive: &interactive
  tty: true        # docker run -t
  stdin_open: true # docker run -i

x-command: &command
  # command: sh -c "make installcheck"
  command: sh -c "bash"

x-pgdata: &pgdata
  PGDATA: /var/lib/postgresql/data
  PGLOG: /var/log/postgresql/postgresql-main.log

x-build-args: &build-args
  context: .
  args:
    <<: *pgdata

x-environment: &environment
  environment:
    USE_DOTNETBUILD: "FALSE"
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DATABASE_CONNECTION_STRING: "Host=127.0.0.1;Port=5432;Username=postgres;Password=postgres;Database=postgres"
    <<: *pgdata

x-ports: &ports
  ports:
    - "5432:5432"

services:
  pldotnet-ubuntu22-dev: &pldotnet-current-container
    container_name: pldotnet-ubuntu22-dev
    image: pldotnet:ubuntu22-dev
    <<: [*interactive, *command, *environment, *ports]
    build:
      dockerfile: docker/Dockerfile_ubuntu22-dev
      <<: *build-args
    volumes:
      - ./:/app/pldotnet/
      - ./postgres-data/ubuntu22:/var/lib/postgresql/data

  pldotnet-ubuntu22:
    container_name: pldotnet-ubuntu22
    image: pldotnet:ubuntu22
    <<: [*interactive, *environment, *ports]
    build:
      context: .
      dockerfile: docker/Dockerfile_ubuntu22

  postgres-pldotnet:
    container_name: postgres-pldotnet
    image: postgres-pldotnet:15-bullseye
    <<: [*interactive, *environment, *ports]
    build:
      context: .
      dockerfile: docker/Dockerfile_postgres-pldotnet

  pldotnet-build:
    container_name: pldotnet-build
    image: pldotnet:build
    <<: [*interactive, *environment]
    command: sh -c "make pldotnet-build-debian-packages"
    build:
      dockerfile: docker/Dockerfile_deb-build
      <<: *build-args
    volumes:
      - ./dotnet_src/:/app/pldotnet/dotnet_src/
      - ./src/:/app/pldotnet/src/
      - ./Makefile:/app/pldotnet/Makefile
      - ./pldotnet.control:/app/pldotnet/pldotnet.control
      - ./pldotnet--0.9.sql:/app/pldotnet/pldotnet--0.9.sql
      - ./tests/:/app/pldotnet/tests/
      - ./automated_test_results/:/app/pldotnet/automated_test_results/
      - ./debian/packages/:/app/pldotnet/debian/packages/
      - ./debian/changelog:/app/pldotnet/debian/changelog
      - ./debian/control.in:/app/pldotnet/debian/control.in
      - ./debian/copyright:/app/pldotnet/debian/copyright
      - ./debian/pgversions:/app/pldotnet/debian/pgversions
      - ./debian/rules:/app/pldotnet/debian/rules
      - ./debian/postinst:/app/pldotnet/debian/postinst

  pldotnet-build-arm:
    container_name: pldotnet-build-arm
    image: pldotnet:build
    <<: [*interactive, *environment]
    command: sh -c "bash /app/pldotnet/docker/scripts/build_packages.sh"
    build:
      dockerfile: docker/Dockerfile_ubuntu-build-arm
      <<: *build-args
    volumes:
      - ./src/:/app/pldotnet/src/
      - ./Makefile:/app/pldotnet/Makefile
      - ./dotnet_src/:/app/pldotnet/dotnet_src/
      - ./tests/:/app/pldotnet/tests/
      - ./debian/packages/:/app/pldotnet/debian/packages/
      - ./debian/pgversions-arm:/app/pldotnet/debian/pgversions
      - ./debian/rules:/app/pldotnet/debian/rules
