FROM ubuntu:22.04

# avoids tzdata prompt
ARG DEBIAN_FRONTEND=noninteractive

# Install PostgreSQL and other dependencies
RUN apt update && \
    apt install -y \
    wget \
    libglib2.0-dev \
    lsb-release \
    postgresql-14 \
    postgresql-common \
    postgresql-server-dev-all \
    sudo

# Install Dotnet
RUN wget -q \
		https://packages.microsoft.com/config/$(lsb_release -i | cut -f2 -d'	' | sed 's/.*/\L&/')/$(lsb_release -r | cut -f2 -d'	')/packages-microsoft-prod.deb \
		-O packages-microsoft-prod.deb

RUN dpkg -i packages-microsoft-prod.deb

RUN rm packages-microsoft-prod.deb

RUN apt update && \
    apt install -y \
    dotnet-runtime-deps-6.0 \
    dotnet-hostfxr-6.0=6.0.8-1 \
    dotnet-runtime-6.0=6.0.8-1 \
    dotnet-sdk-6.0=6.0.400-1

# Install pldotnet
COPY ./debian/packages /app/pldotnet/packages
RUN dpkg -i /app/pldotnet/packages/postgresql-14-pldotnet_0.9-1_amd64.deb


ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Set the locale
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8

# pgdata
ARG PGDATA
ENV PGDATA=${PGDATA}

# TODO: Change this using wget from the official repository
COPY ./docker/scripts/install_pldotnet_deb.sh /install_pldotnet_deb.sh
COPY ./docker/scripts/ubuntu22_entrypoint.sh /ubuntu22_entrypoint.sh

# Start PostgreSQL service
# RUN service postgresql start
RUN ./install_pldotnet_deb.sh

RUN apt-get clean
RUN apt-get autoremove

WORKDIR /var/lib/PlDotNET/samples

ENTRYPOINT /ubuntu22_entrypoint.sh