FROM postgres:15.1-bullseye

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

# Do all the things
RUN apt update &&  apt install make
RUN make -f /app/pldotnet/docker/scripts/Makefile-builder deb_build

ENTRYPOINT []
