#!/bin/bash
# FIXME: remove plcsharp and plfsharp from postgresql before removing
# the package.
set -e

# Starting PG server
(runuser -u postgres -- initdb) || true
(runuser -u postgres -- pg_ctl start) || true
service postgresql start

runuser -u postgres -- psql -c "DROP EXTENSION IF EXISTS pldotnet CASCADE;"
